// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjMOEpge8qs5es2C9aDaJx9__yv2Jq6v8',
    appId: '1:837786858873:web:320a4c88da92398b6f2ba8',
    messagingSenderId: '837786858873',
    projectId: 'myfirstnotes-123bc',
    authDomain: 'myfirstnotes-123bc.firebaseapp.com',
    storageBucket: 'myfirstnotes-123bc.appspot.com',
    measurementId: 'G-DMXQJQKD4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexDYqn4KNmtA1ImdjAK426WfB1A08AwI',
    appId: '1:837786858873:android:8694d8a83d948e2b6f2ba8',
    messagingSenderId: '837786858873',
    projectId: 'myfirstnotes-123bc',
    storageBucket: 'myfirstnotes-123bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-SEDZA5lqe4E6OeKiBsEFsA_ku0SJYY8',
    appId: '1:837786858873:ios:bacba6f181e382d96f2ba8',
    messagingSenderId: '837786858873',
    projectId: 'myfirstnotes-123bc',
    storageBucket: 'myfirstnotes-123bc.appspot.com',
    iosClientId: '837786858873-j5mmji2hhg105836jnqh181q704q30sb.apps.googleusercontent.com',
    iosBundleId: 'com.thewebpeople',
  );
}
